version: '3.8'
services:
  wallet:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wallet-service
    ports:
      - 4022:4022
    networks:
      - samagra_compass

networks:
  samagra_compass:
    external: true
